# bg opacity
background_opacity 0.2
dynamic_background_opacity yes
map ctrl+shift+up   set_background_opacity +0.05
map ctrl+shift+down set_background_opacity -0.05

# font
font_size 16.0
font_family Source Code Pro
confirm_os_window_close 0

symbol_map U+E000-U+F8FF Symbols Nerd Font
symbol_map U+F0001-U+F1AF0 Symbols Nerd Font

shell /usr/bin/fish


# BEGIN_KITTY_THEME
# Base2Tone Drawbridge Dark
include current-theme.conf
# END_KITTY_THEME
